version: '3.4'

services:
  fetchassessment:
    image: fetchassessment
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
